# Site settings

title: Nickel Based Superalloy Design Model
header-img: img/home-bg.jpg
email: david.brough.0416@gmail.com
description: "An approach with a modular workflow"
baseurl: "/ni_super_alloy_design"
url: "http://mined-gatech.github.io"
github_username:  mined-gatech
project_repository: ni_super_alloy_design
disqus_shortname: ni_super_alloy_design

# Build settings
# Don't change these variables
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
